# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-03-28 17:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Student', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question_Papers',
            fields=[
                ('qpID', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('qpName', models.CharField(max_length=30)),
                ('timeDuration', models.DecimalField(decimal_places=3, max_digits=8)),
                ('createdOn', models.DateField(auto_now=True)),
                ('activeFlag', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('questionID', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('statement', models.TextField(max_length=200)),
                ('optionA', models.CharField(max_length=50)),
                ('optionB', models.CharField(max_length=50)),
                ('optionC', models.CharField(max_length=50)),
                ('optionD', models.CharField(max_length=50)),
                ('correctOption', models.CharField(max_length=1)),
                ('image1', models.ImageField(default=None, upload_to='pic_folder/')),
                ('image2', models.ImageField(default=None, upload_to='pic_folder/')),
                ('maxMarks', models.DecimalField(decimal_places=3, max_digits=6)),
                ('subject', models.CharField(default='NA', max_length=20)),
                ('subCategory', models.CharField(max_length=20)),
                ('difficultyLevel', models.IntegerField(default=2)),
                ('timeLimit', models.DecimalField(decimal_places=3, max_digits=8)),
            ],
        ),
        migrations.CreateModel(
            name='Records',
            fields=[
                ('recordID', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('fromTime', models.TimeField(auto_now=True)),
                ('tillTime', models.TimeField(auto_now=True)),
                ('response', models.CharField(max_length=2)),
                ('questionID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Question_Bank.Questions')),
                ('studentID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Student.Students')),
            ],
        ),
    ]
