# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-03-28 18:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Question_Bank', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question_Analytics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attemptedCount', models.IntegerField(default=0, max_length=5)),
                ('correctAttempts', models.IntegerField(default=0, max_length=5)),
                ('wrongAttempts', models.IntegerField(default=0, max_length=5)),
                ('avgTimeTaken', models.DecimalField(decimal_places=3, max_digits=8)),
                ('questionID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Question_Bank.Questions')),
            ],
        ),
        migrations.CreateModel(
            name='Question_Paper_Analytics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avgScore', models.DecimalField(decimal_places=3, max_digits=8)),
                ('topScore', models.DecimalField(decimal_places=3, max_digits=8)),
                ('attemptCount', models.IntegerField(default=0, max_length=5)),
            ],
        ),
        migrations.AddField(
            model_name='question_papers',
            name='toughnessLevel',
            field=models.IntegerField(default=2, max_length=2),
        ),
        migrations.AddField(
            model_name='question_paper_analytics',
            name='qpID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Question_Bank.Question_Papers'),
        ),
    ]
