# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-03-29 15:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Question_Bank', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='questions',
            old_name='optionA',
            new_name='incorrectOption1',
        ),
        migrations.RenameField(
            model_name='questions',
            old_name='optionB',
            new_name='incorrectOption2',
        ),
        migrations.RenameField(
            model_name='questions',
            old_name='optionC',
            new_name='incorrectOption3',
        ),
        migrations.RemoveField(
            model_name='questions',
            name='optionD',
        ),
        migrations.RemoveField(
            model_name='questions',
            name='questionID',
        ),
        migrations.AddField(
            model_name='questions',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='questions',
            name='correctOption',
            field=models.CharField(max_length=50),
        ),
    ]
