# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-03-29 16:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Question_Bank', '0002_auto_20180329_1531'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='maxMarks',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='questions',
            name='timeLimit',
            field=models.IntegerField(),
        ),
    ]
