# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-03-28 18:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Question_Bank', '0002_auto_20180328_2339'),
        ('Student', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student_Attempt_Result_Summary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attemptedFlag', models.BooleanField(default=False)),
                ('startTime', models.TimeField(auto_now=True)),
                ('endTime', models.TimeField()),
                ('difficultyLevel1Score', models.DecimalField(decimal_places=3, max_digits=8)),
                ('difficultyLevel2Score', models.DecimalField(decimal_places=3, max_digits=8)),
                ('difficultyLevel3Score', models.DecimalField(decimal_places=3, max_digits=8)),
                ('difficultyLevel4Score', models.DecimalField(decimal_places=3, max_digits=8)),
                ('difficultyLevel5Score', models.DecimalField(decimal_places=3, max_digits=8)),
                ('qpID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Question_Bank.Question_Papers')),
            ],
        ),
        migrations.CreateModel(
            name='Student_Response',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response', models.CharField(max_length=2)),
                ('correctOption', models.CharField(max_length=2)),
                ('marks', models.DecimalField(decimal_places=3, max_digits=6)),
                ('qpID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Question_Bank.Question_Papers')),
                ('questionID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Question_Bank.Questions')),
            ],
        ),
        migrations.CreateModel(
            name='Student_Summary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.DecimalField(decimal_places=3, max_digits=8)),
                ('difficultyLevel1Score', models.DecimalField(decimal_places=3, max_digits=8)),
                ('difficultyLevel2Score', models.DecimalField(decimal_places=3, max_digits=8)),
                ('difficultyLevel3Score', models.DecimalField(decimal_places=3, max_digits=8)),
                ('difficultyLevel4Score', models.DecimalField(decimal_places=3, max_digits=8)),
                ('difficultyLevel5Score', models.DecimalField(decimal_places=3, max_digits=8)),
            ],
        ),
        migrations.AddField(
            model_name='students',
            name='name',
            field=models.CharField(default='NA', max_length=50),
        ),
        migrations.AddField(
            model_name='students',
            name='password',
            field=models.CharField(default='123456', max_length=15),
        ),
        migrations.AddField(
            model_name='student_summary',
            name='studentID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Student.Students'),
        ),
        migrations.AddField(
            model_name='student_response',
            name='studentID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Student.Students'),
        ),
        migrations.AddField(
            model_name='student_attempt_result_summary',
            name='studentID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Student.Students'),
        ),
    ]
